author: Zichun Qiu, Enyi Yan, Liqian Yan, Yuezhe Tan
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
keywords: nona
description: "XJP LifeCompanion AI"